# Original source: https://github.com/vector-im/element-desktop/blob/master/.github/workflows/build_linux.yaml

# This workflow relies on actions/cache to store the hak dependency artifacts as they take a long time to build
# Due to this extra care must be taken to only ever run all build_* scripts against the same branch to ensure
# the correct cache scoping, and additional care must be taken to not run untrusted actions on the develop branch.
on:
    workflow_call:
        secrets:
            USER_HOMESERVER:
                required: true
            USER_UPDATE_FOLDER:
                required: true
            NAMING_APP_ID:
                required: true
            NAMING_APP_NAME_SUFFIX:
                required: false
            NAMING_APP_DATA_NAME_SUFFIX:
                required: false
        inputs:
            config:
                type: string
                required: true
                description: "The config directory to use"
            sqlcipher:
                type: string
                required: true
                description: "How to link sqlcipher, one of 'system' | 'static'"
            element-version:
                description: Version of Element to build
                required: true
                type: string
            update-policy:
                type: string
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/vector-im/element-desktop-dockerbuild:t3chguy-dockerbuild
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3

            - name: Load Element & Create Config
              run: |
                  git clone https://github.com/vector-im/element-desktop.git
                  cd element-desktop
                  git checkout master
                  git checkout ${{ inputs.element-version }}
                  cd ..

                  mkdir myconfig
                  cp element-desktop/element.io/release/config.json myconfig/config.json
                  sed -i 's#\"default_server_name\": \"matrix.org\",#\"default_server_name\": \"${{ secrets.USER_HOMESERVER }}\",#g' myconfig/config.json

                  if [[ "${{ inputs.update-policy }}" == "custom" ]]; then
                     sed -i 's#\"update_base_url\": \"https://packages.element.io/desktop/update/\",#\"update_base_url\": \"${{ secrets.USER_UPDATE_FOLDER }}\",#g' myconfig/config.json;
                  fi

                  if [[ "${{ inputs.update-policy }}" == "none" ]]; then
                      sed -i 's#\"update_base_url\": \"https://packages.element.io/desktop/update/\",##g' myconfig/config.json;
                  fi
                  
                  sed -i 's#\"name\": \"element-desktop\"#\"name\": \"element-desktop${{ secrets.NAMING_APP_DATA_NAME_SUFFIX }}\"#g' element-desktop/package.json
                  sed -i 's#\"productName\": \"Element\"#\"productName\": \"Element${{ secrets.NAMING_APP_NAME_SUFFIX }}\"#g' element-desktop/package.json

                  mv element-desktop/* ./

            - uses: actions/download-artifact@v3
              with:
                  name: webapp

            - name: Cache .hak
              id: cache
              uses: actions/cache@v3
              with:
                  key: ${{ runner.os }}-${{ hashFiles('hakDependencies.json', 'electronVersion') }}
                  path: |
                      ./.hak

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"
              env:
                  # Workaround for https://github.com/actions/setup-node/issues/317
                  FORCE_COLOR: 0

            # Does not need branch matching as only analyses this layer
            - name: Install Deps
              run: "yarn install --pure-lockfile"
            
            - name: Change config
              run: "yarn run fetch --noverify --cfgdir myconfig"

            - name: Build Natives
              if: steps.cache.outputs.cache-hit != 'true'
              run: "yarn build:native"
              env:
                  SQLCIPHER_STATIC: ${{ inputs.sqlcipher == 'static' && '1' || '' }}

            #- name: "[Nightly] Resolve version"
            #  id: nightly
            #  if: inputs.version != ''
            #  run: |
            #      echo "config-args=--nightly '${{ inputs.version }}'" >> $GITHUB_OUTPUT

            - name: Generate debian files and arguments
              id: debian
              run: |
                  if [ -f changelog.Debian ]; then
                      echo "config-args=--deb-changelog changelog.Debian" >> $GITHUB_OUTPUT
                  fi
                  
                  cp "$DIR/control.template" debcontrol
                  VERSION=${INPUT_VERSION:-$(cat package.json | jq -r .version)}
                  echo "Version: ${VERSION:1}" >> debcontrol
              env:
                  DIR: ${{ inputs.config }}
                  INPUT_VERSION: ${{ inputs.element-version }}

            - name: Build App
              run: |
                  npx ts-node scripts/generate-builder-config.ts ${{ steps.nightly.outputs.config-args }} --deb-custom-control=debcontrol

                  sed -i 's#\"productName\": \"Element\"#\"productName\": \"Element${{ secrets.NAMING_APP_NAME_SUFFIX }}\"#g' electron-builder.json
                  sed -i 's#\"appId\": \"im.riot.app\"#\"appId\": \"${{ secrets.NAMING_APP_ID }}\"#g' electron-builder.json

                  yarn build --publish never -l --config electron-builder.json

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: linux-sqlcipher-${{ inputs.sqlcipher }}
                  path: dist
                  retention-days: 1
