name: Simple Job On Different OS

on:
  workflow_dispatch:

jobs:
  write:
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: First Step
      run: echo "success"

    - name: Build
      run: yarn build-custom
