name: Simple Job On Different OS

on:
  workflow_dispatch:

jobs:
  write:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: First Step
        run: echo "success"
