name: Build

on:
  workflow_dispatch:

jobs:
  test_job:
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          yarn load v1.11.28
          yarn mv-to-root
          yarn
          mkdir myconfig
          yarn create-config mtrx.intra.getzen.dev
          yarn set-confing v1.11.28

