# Original source: https://github.com/vector-im/element-desktop/blob/master/.github/workflows/build_and_deploy.yaml

name: Build and Deploy
on:
    ## Nightly build
    #schedule:
    #    - cron: "0 9 * * *"
    # Manual nightly & release
    workflow_dispatch:
        inputs:
            mode:
                description: What type of build to trigger. Release builds MUST be ran from the `master/main` branch.
                required: true
                default: release
                type: choice
                options:
                    - release
            macos:
                description: Build macOS
                required: true
                type: boolean
                default: true
            windows_32bit:
                description: Build Windows 32-bit
                required: true
                type: boolean
                default: true
            windows_64bit:
                description: Build Windows 64-bit
                required: true
                type: boolean
                default: true
            linux:
                description: Build Linux
                required: true
                type: boolean
                default: true
            element-version:
                description: Version of Element to build
                required: true
                type: string
                default: v1.11.28
            short-version:
                required: true
                type: string
                default: 1.11.28
            update-policy:
                required: true
                default: custom
                type: choice
                options:
                    - custom
                    - original
                    - none
    workflow_call:
        secrets:
            APPLE_ID:
                required: false
            APPLE_ID_PASSWORD:
                required: false
            APPLE_TEAM_ID:
                required: false
            APPLE_CSC_KEY_PASSWORD:
                required: false
            APPLE_CSC_LINK:
                required: false
            USER_HOMESERVER:
                required: true
            USER_UPDATE_FOLDER:
                required: true
            API:
                required: true
            API_ACCESS_KEY:
                required: true
            API_SECRET_KEY:
                required: true
            API_BUCKET_NAME:
                required: true
            NAMING_APP_ID:
                required: true
            NAMING_APP_NAME_SUFFIX:
                required: false
            NAMING_APP_DATA_NAME_SUFFIX:
                required: false
        inputs:
            mode:
                type: string
            macos:
                type: boolean
            windows_32bit:
                type: boolean
            windows_64bit:
                type: boolean
            linux:
                type: boolean
            element-version:
                type: string
            short-version:
                type: string
            update-policy:
                type: string

concurrency: ${{ github.workflow }}
env:
    R2_BUCKET: "packages-element-io"
jobs:
    prepare:
        uses: ./.github/workflows/build_prepare.yaml
        secrets: inherit
        with:
            config: element.io/${{ inputs.mode || 'nightly' }}
            nightly: ${{ inputs.mode != 'release' }}
            element-version: ${{ inputs.element-version }}
            update-policy: ${{ inputs.update-policy }}
    
    windows_32bit:
        if: github.event_name != 'workflow_dispatch' || inputs.windows_32bit
        needs: prepare
        name: Windows 32-bit
        uses: ./.github/workflows/build_windows.yaml
        secrets: inherit
        with:
            deploy-mode: true
            arch: x86
            element-version: ${{ inputs.element-version }}
            update-policy: ${{ inputs.update-policy }}

    windows_64bit:
        if: github.event_name != 'workflow_dispatch' || inputs.windows_64bit
        needs: prepare
        name: Windows 64-bit
        uses: ./.github/workflows/build_windows.yaml
        secrets: inherit
        with:
            deploy-mode: true
            arch: x64
            element-version: ${{ inputs.element-version }}
            update-policy: ${{ inputs.update-policy }}

    macos:
        if: github.event_name != 'workflow_dispatch' || inputs.macos
        needs: prepare
        name: macOS
        uses: ./.github/workflows/build_macos.yaml
        secrets: inherit
        with:
            sign: true
            deploy-mode: true
            base-url: https://packages.element.io/${{ inputs.mode == 'release' && 'desktop' || 'nightly' }}
            element-version: ${{ inputs.element-version }}
            update-policy: ${{ inputs.update-policy }}

    linux:
        if: github.event_name != 'workflow_dispatch' || inputs.linux
        needs: prepare
        name: Linux
        uses: ./.github/workflows/build_linux.yaml
        secrets: inherit
        with:
            config: element.io/${{ inputs.mode || 'nightly' }}
            sqlcipher: system
            element-version: ${{ inputs.element-version }}
            update-policy: ${{ inputs.update-policy }}
    
    add-to-releases:
        permissions: write-all
        needs: [prepare, linux, windows_32bit, windows_64bit, macos]
        uses: ./.github/workflows/add_to_releases.yaml
        secrets: inherit
        with:
            element-version: ${{ inputs.element-version }}
            short-version: ${{ inputs.short-version }}
    
    deploy:
        permissions: write-all
        needs: [prepare, linux, windows_32bit, windows_64bit, macos]
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
