name: Check New Versions

on:
  workflow_dispatch:
    inputs:
      days:
        required: true
        type: choice
        options:
          - '1'
          - '365'
        default: '1'
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-date:
    runs-on: ubuntu-latest
    outputs:
      needs-rebuild: ${{ steps.check.outputs.needs-rebuild }}
      element-version: ${{ steps.check.outputs.element-version }}
      short-version: ${{ steps.check.outputs.short-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Check
        id: check
        run: |
          git clone https://github.com/vector-im/element-desktop.git
          cd element-desktop

          usince=$(date -Iminutes -d "1 day ago 20 minutes ago")
          if [[ "${{ inputs.days }}" == "365" ]]; then
            usince=$(date -Iminutes -d "365 days ago");
          fi
          
          echo $usince
          lst=$(git log --grep='^v[0-9]*\.[0-9]*\.[0-9]*$' --max-count=1 --oneline --no-decorate --since="$usince")
          if [[ "$lst" == "" ]]; then 
            echo "needs-rebuild=false" >> "$GITHUB_OUTPUT";
          else 
            echo "needs-rebuild=true" >> "$GITHUB_OUTPUT";
            echo "element-version=${lst:8}" >> "$GITHUB_OUTPUT";
            echo "short-version=${lst:9}" >> "$GITHUB_OUTPUT";
            echo $lst
          fi
  
  build:
    permissions: write-all
    needs: check-date
    if: needs.check-date.outputs.needs-rebuild == 'true'
    uses: ./.github/workflows/build_and_deploy.yaml
    secrets: inherit
    with:
      mode: "release"
      macos: true
      windows_32bit: true
      windows_64bit: true
      linux: true
      element-version: ${{ needs.check-date.outputs.element-version }}
      short-version: ${{ needs.check-date.outputs.short-version }}
      naming: "custom-hs"
