on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/vector-im/element-desktop.git
          cd element-desktop
          usince=$(date -Iminutes -d "100 days ago")
          echo $usince
          git log --grep='^v[0-9]*\.[0-9]*\.[0-9]*$' --max-count=100 --oneline --no-decorate --since="$usince"
