on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  check-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/vector-im/element-desktop.git
          cd element-desktop
          usince=$(date -Iminutes -d "1 day ago")
          echo $usince
          lst=$(git log --grep='^v[0-9]*\.[0-9]*\.[0-9]*$' --max-count=1 --oneline --no-decorate --since="$usince")
          if [[ "$lst" == "" ]]; then echo "No updates last day." ; else echo "OK"; fi
