on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      #- uses: actions/download-artifact@v3
      #  with:
      #      path: packages.element.io
      #      name: packages.element.io
      
      #- run: ls -R

      - run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc

          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/

          mc --help

