on:
  workflow_call:
    secrets:
      API:
        required: true
      API_ACCESS_KEY:
        required: true
      API_SECRET_KEY:
        required: true
      API_BUCKET_NAME:
        required: true
      NAMING_APP_ID:
          required: true
      NAMING_APP_NAME_SUFFIX:
          required: false
      NAMING_APP_DATA_NAME_SUFFIX:
          required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
        with:
            path: packages.element.io
            name: packages.element.io
      
      - run: ls -R

      - run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc

          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/

          mc alias set wr "$API" "$ACCESS_KEY" "$SECRET_KEY"
          mc cp --recursive packages.element.io/ wr/"$BUCKET_NAME"/
        env:
          API: ${{ secrets.API }}
          ACCESS_KEY: ${{ secrets.API_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          BUCKET_NAME: ${{ secrets.API_BUCKET_NAME }}
        name: Deploy
