on:
  workflow_call:
    secrets:
      api:
        required: true
      access_key:
        required: true
      secret_key:
        required: true
      bucket_name:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
        with:
            path: packages.element.io
            name: packages.element.io
      
      - run: ls -R

      - run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc

          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/

          mc alias set wr "$API" "$ACCESS_KEY" "$SECRET_KEY"
          mc cp --recursive packages.element.io/ wr/"$BUCKET_NAME"/
        env:
          API: ${{ secrets.api }}
          ACCESS_KEY: ${{ secrets.access_key }}
          SECRET_KEY: ${{ secrets.secret_key }}
          BUCKET_NAME: ${{ secrets.bucket_name }}
        name: Deploy
